<template>
  <hot-table :data="data" :settings="settings"></hot-table>
</template>

<script>
  import { HotTable } from '@handsontable/vue';

  export default {
    data: function() {
      return {
        data: [
			["all.ehentai", "E-Hentai", "e-hentai.org", "Multi"],
			["all.mangaplus", "MANGA Plus by SHUEISHA", "mangaplus.shueisha.co.jp", "Multi"],
			["all.mangadex", "MangaDex", "mangadex.org", "Multi"],
			["all.nhentai", "NHentai", "nhentai.net", "Multi"],
			["all.ninemanga", "NinaManga", "ninemanga.com", "Multi"],
			["all.simplyhentai", "Simply Hentai", "simply-hentai.com", "Multi"],
			["all.toomics", "Toomics", "toomics.com", "Multi"],
			["all.boommanga", "BoomManga", "m.boommanga.com", "EN"],
			["all.boommanga", "ManManga", "m.manmanga.com", "EN"],
			["all.boommanga", "TwinsComics", "m.twinscomics.com", "EN"],
			["all.boommanga", "BoomMangazh", "m.boommanga.com/cn", "ZH"],
			["all.boommanga", "ManMangazh", "m.manmanga.com/cn", "ZH"],
			["all.boommanga", "TwinsComicszh", "m.twinscomics.com/cn", "ZH"],
			["all.comicake", "LetItGo Scans", "https://reader.letitgo.scans.today", "EN"],
			["all.comicake", "ProjectTime Scans", "read.ptscans.com", "EN"],
			["all.comicake", "WhimSubs", "https://whimsubs.xyz", "EN"],
			["all.fmreader", "18LHPlus", "18lhplus.com", "EN"],
			["all.fmreader", "Comicastle", "www.comicastle.org", "EN"],
			["all.fmreader", "LHTranslation", "lhtranslation.net", "EN"],
			["all.fmreader", "MangaBone", "mangabone.com", "EN"],
			["all.fmreader", "MangaBorn", "hellxlight.com", "EN"],
			["all.fmreader", "Manhwa18", "manhwa18.com", "EN"],
			["all.fmreader", "Manhwa18.net", "manhwa18.net", "EN"],
			["all.fmreader", "ManhwaScan", "manhwascan.com", "EN"],
			["all.fmreader", "ReadComicOnlineOrg", "readcomiconline.org", "EN"],
			["all.fmreader", "YoloManga", "yolomanga.ca", "ES"],
			["all.fmreader", "HanaScan (Raw QQ)", "rawqq.com", "JA"],
			["all.fmreader", "MangaHato", "mangahato.com", "JA"],
			["all.fmreader", "MangaTiki", "mangatiki.com", "JA"],
			["all.fmreader", "RawLH", "loveheaven.net", "JA"],
			["all.fmreader", "Manhwa18.net Raw", "manhwa18.net", "KO"],
			["all.fmreader", "MangaTR", "manga-tr.com", "TR"],
			["all.fmreader", "AiLoveManga", "ailovemanga.com", "VI"],
			["all.fmreader", "TruyenTranhLH", "truyentranhlh.net", "VI"],
			["all.foolslide", "MangaScouts", "mangascouts.org", "DE"],
			["all.foolslide", "Anata No Motokare", "https://motokare.xyz/reader/", "EN"],
			["all.foolslide", "Death Toll Scans", "deathtollscans.net", "EN"],
			["all.foolslide", "DKThias Scanlations", "dkthias.com", "EN"],
			["all.foolslide", "Doki Fansubs", "kobato.hologfx.com", "EN"],
			["all.foolslide", "Evil Flowers", "evilflowers.com", "EN"],
			["all.foolslide", "Helvetica Scans", "helveticascans.com", "EN"],
			["all.foolslide", "Iskultrip Scans", "maryfaye.net", "EN"],
			["all.foolslide", "Jaiminis Box", "jaiminisbox.com", "EN"],
			["all.foolslide", "Kirei Cake", "kireicake.com", "EN"],
			["all.foolslide", "Lilyreader", "smuglo.li", "EN"],
			["all.foolslide", "Mangatellers", "mangatellers.gr", "EN"],
			["all.foolslide", "Midnight Haven", "midnighthaven.shounen-ai.net", "EN"],
			["all.foolslide", "One Time Scans", "otscans.com", "EN"],
			["all.foolslide", "Sense Scans", "sensescans.com", "EN"],
			["all.foolslide", "Silent Sky", "Silentskys-scans.net", "EN"],
			["all.foolslide", "The Cat Scans", "reader2.thecatscans.com", "EN"],
			["all.foolslide", "World Three", "Slide-world-three.org", "EN"],
			["all.foolslide", "Yuri-ism", "yuri-ism.net/slide", "EN"],
			["all.foolslide", "Zandy no Fansub", "zandynofansub.aishiteru.org", "EN"],
			["all.foolslide", "HentaiCafe", "https://hentai.cafe", "EN/mixed"],
			["all.foolslide", "Kirishima Fansub", "kirishimafansub.net", "ES"],
			["all.foolslide", "Ajia no Scantrad", "ajianoscantrad.fr", "FR"],
			["all.foolslide", "LupiTeam", "lupiteam.net", "IT"],
			["all.foolslide", "PowerManga", "reader.powermanga.org", "IT"],
			["all.foolslide", "Storm in Heaven", "Storm-in-heaven.net", "IT"],
			["all.foolslide", "Baixar Hentai", "leitura.baixarhentai.net", "PT"],
			["all.foolslide", "AkaiYuhiMun Team", "akaiyuhimun.ru", "RU"],
			["all.foolslide", "Russification / Русификация", "rusmanga.ru", "RU"],
			["all.genkan", "Edelgarde Scans", "edelgardescans.com", "EN"],
			["all.genkan", "Hatigarm Scans", "hatigarmscanz.net", "EN"],
			["all.genkan", "Hunlight Scans", "hunlight-scans.info", "EN"],
			["all.genkan", "Leviatan Scans", "leviatanscans.com", "EN"],
			["all.genkan", "One Shot Scans", "oneshotscans.com", "EN"],
			["all.genkan", "Reaper Scans", "reaperscams.com", "EN"],
			["all.genkan", "SecretScans", "secretscans.co", "EN"],
			["all.genkan", "The Nonames Scans", "the-nonames.com", "EN"],
			["all.genkan", "Wowe Scans", "https://wowescans.co", "EN"],
			["all.genkan", "ZeroScans", "zeroscans.com", "EN"],
			["all.genkan", "Leviatan Scans", "es.leviatanscans.com", "ES"],
			["all.madara", "Azora", "azoramanga.com", "AR"],
			["all.madara", "KingzManga", "kingzmanga.com", "AR"],
			["all.madara", "Manga Action", "manga-action.com", "AR"],
			["all.madara", "Niji Translations", "niji-translations.com", "AR"],
			["all.madara", "مانجا العاشق", "https://3asq.org", "AR"],
			["all.madara", "مانجا عرب تيم", "mangaarabteam.com", "AR"],
			["all.madara", "مانجا ليك", "mangalek.com", "AR"],
			["all.madara", "موقع لترجمة المانجا", "golden-manga.ml", "AR"],
			["all.madara", "1st Kiss Manga", "1stkissmanga.com", "EN"],
			["all.madara", "365Manga", "365manga.com", "EN"],
			["all.madara", "AllPornComic", "allporncomic.com", "EN"],
			["all.madara", "AoC Translations", "https://aoc.moe", "EN"],
			["all.madara", "Astral Library", "astrallibrary.net", "EN"],
			["all.madara", "Chibi Manga", "www.cmreader.info", "EN"],
			["all.madara", "Disaster Scans", "disasterscans.com", "EN"],
			["all.madara", "EarlyManga", "https://earlymanga.website", "EN"],
			["all.madara", "GetManhwa", "getmanhwa.co", "EN"],
			["all.madara", "Happy Tea Scans", "happyteascans.com", "EN"],
			["all.madara", "Hiperdex", "hiperdex.com", "EN"],
			["all.madara", "Isekai Scan", "isekaiscan.com", "EN"],
			["all.madara", "Kissmanga.in", "kissmanga.in", "EN"],
			["all.madara", "Lily Manga", "lilymanga.com", "EN"],
			["all.madara", "Luxy Scans", "luxyscans.com", "EN"],
			["all.madara", "MangaBob", "mangabob.com", "EN"],
			["all.madara", "MangaDods", "www.mangadods.com", "EN"],
			["all.madara", "MangaKiss", "mangakiss.org", "EN"],
			["all.madara", "MangaKomi", "mangakomi.com", "EN"],
			["all.madara", "Mangasushi", "mangasuhi.net", "EN"],
			["all.madara", "MangaSY", "www.mangasy.com", "EN"],
			["all.madara", "MangaTX", "mangatx.com", "EN"],
			["all.madara", "MangazukiMe", "mangazuki.me", "EN"],
			["all.madara", "MangazukiOnline", "https://www.mangazuki.online", "EN"],
			["all.madara", "Manhwa Club", "https://manhwa.club", "EN"],
			["all.madara", "ManhwaHentaiMe", "https://manhwahentai.me", "EN"],
			["all.madara", "Many Toon", "manytoon.com", "EN"],
			["all.madara", "Milftoon", "https://milftoon.xxx", "EN"],
			["all.madara", "Miracle Scans", "miraclescans.com", "EN"],
			["all.madara", "Night Comic", "www.nightcomic.com", "EN"],
			["all.madara", "NinjaScans", "ninjascans.com", "EN"],
			["all.madara", "OnManga", "onmanga.com", "EN"],
			["all.madara", "Plot Twist No Fansub", "www.plotwistscan.com/", "EN"],
			["all.madara", "ReadManhua", "readmanhua.net", "EN"],
			["all.madara", "Teabeer Comics", "https://teabeercomics.com", "EN"],
			["all.madara", "Toonily", "toonily.com", "EN"],
			["all.madara", "Wakamics", "wakamics.com", "EN"],
			["all.madara", "Wordrain69", "https://wordrain69.com/", "EN"],
			["all.madara", "Wuxia World", "https://wuxiaworld.site", "EN"],
			["all.madara", "Yo Manga", "yomanga.info", "EN"],
			["all.madara", "Zin Translator", "zinmanga.com", "EN"],
			["all.madara", "DoujinHentai", "doujinhentai.net", "ES"],
			["all.madara", "Hunter Fansub", "hunterfansub.com", "ES"],
			["all.madara", "ZManga", "zmanga.org", "ES"],
			["all.madara", "ATM-Subs", "atm-subs.fr", "FR"],
			["all.madara", "Novel France", "novel-france.fr", "FR"],
			["all.madara", "Tsubaki No Scan", "tsubakinoscan.com", "FR"],
			["all.madara", "Yokai Jump", "yokaijump.fr", "FR"],
			["all.madara", "Indian Comics Online", "www.indiancomicsonline.com", "HI"],
			["all.madara", "KlikManga", "klikmanga.com", "ID"],
			["all.madara", "Komik Go", "komikgo.com", "ID"],
			["all.madara", "MangaLaw", "mangalaw.com", "JA"],
			["all.madara", "MangazukiClubJP", "https://mangazuki.club", "JA"],
			["all.madara", "MangazukiClubKO", "https://mangazuki.club", "KO"],
			["all.madara", "Ichirin No Hana Yuri", "https://ichirinnohanayuri.com.br", "pt-BR"],
			["all.madara", "Yaoi Toshokan", "www.yaoitoshokan.com.br", "pt-BR"],
			["all.madara", "Just For Fun", "just-for-fun.ru", "RU"],
			["all.madara", "Adonis Fansub", "adonisfansub.com", "TR"],
			["all.mangabox", "ChapterManga", "chaptermanga.com", "EN"],
			["all.mangabox", "Kono-Basho", "kono-basho.com", "EN"],
			["all.mangabox", "Mangabat", "mangabat.com", "EN"],
			["all.mangabox", "Mangafree", "mangafree.online", "EN"],
			["all.mangabox", "Mangakakalot", "mangakakalot.com", "EN"],
			["all.mangabox", "Manganelo", "manganelo.com", "EN"],
			["all.mangabox", "MangaOnl", "mangaonl.com", "EN"],
			["all.mangacards", "Inept Bastards", "https://ineptbastards.xyz", "EN"],
			["all.mangacards", "NANI? Scans", "https://naniscans.xyz", "EN"],
			["all.mangacards", "Valhalla Scans", "valhallascans.com", "EN"],
			["all.mangadventure", "Arc-Relight", "arc-relight.site", "EN"],
			["all.mangadventure", "Decadence Scans", "reader.decadencescans.com", "EN"],
			["all.mangatensei", "Bato.to", "bato.to", "Muli"],
			["all.mangatensei", "Mangawindow", "mangawindow.net", "Muli"],
			["all.mangatensei", "Mangatensei", "www.mangatensei.com", "Multi"],
			["all.mmrcms (my manga reader cms)", "مانجا اون لاين", "onma.me", "AR"],
			["all.mmrcms (my manga reader cms)", "Utsukushii", "manga.utsukushii-bg.com", "BG"],
			["all.mmrcms (my manga reader cms)", "Biamam Scans", "biamam.com", "EN"],
			["all.mmrcms (my manga reader cms)", "Fallen Angels", "manga.fascans.com", "EN"],
			["all.mmrcms (my manga reader cms)", "Mangawww Reader", "https://mangawww.club", "EN"],
			["all.mmrcms (my manga reader cms)", "Read Comics Online", "readcomicsonline.ru", "EN"],
			["all.mmrcms (my manga reader cms)", "White Cloud Pavilion", "www.whitecloudpavilion.com", "EN"],
			["all.mmrcms (my manga reader cms)", "LeoManga", "leomanga.me", "ES"],
			["all.mmrcms (my manga reader cms)", "Mangadoor", "mangadoor.com", "ES"],
			["all.mmrcms (my manga reader cms)", "Mangas.pw", "mangas.in", "ES"],
			["all.mmrcms (my manga reader cms)", "submanga", "https://submanga.li", "ES"],
			["all.mmrcms (my manga reader cms)", "Tumangaonline.co", "tumangaonline.fun", "ES"],
			["all.mmrcms (my manga reader cms)", "Universo Yuri", "universoyuri.com", "ES"],
			["all.mmrcms (my manga reader cms)", "Scan FR", "www.scan-fr.co", "FR"],
			["all.mmrcms (my manga reader cms)", "Scan OP", "scan-op.com", "FR"],
			["all.mmrcms (my manga reader cms)", "Scan VF", "www.scan-vf.net", "FR"],
			["all.mmrcms (my manga reader cms)", "Komikid", "www.komikid.com", "ID"],
			["all.mmrcms (my manga reader cms)", "HentaiShark", "www.hentaishark.com", "Multi"],
			["all.mmrcms (my manga reader cms)", "Dracaena", "dracaena.webd.pl", "PL"],
			["all.mmrcms (my manga reader cms)", "Nikushima", "azbivo.webd.pro", "PL"],
			["all.mmrcms (my manga reader cms)", "Phoenix-Scans", "https://phoenix-scans.pl", "PL"],
			["all.mmrcms (my manga reader cms)", "ToraScans", "torascans.pl", "PL"],
			["all.mmrcms (my manga reader cms)", "Comic Space", "www.comicspace.com.br", "PT"],
			["all.mmrcms (my manga reader cms)", "Mangás Yuri", "mangasyuri.net", "PT"],
			["all.mmrcms (my manga reader cms)", "Japit Comics", "j-comics.ru", "RU"],
			["all.mmrcms (my manga reader cms)", "MangaHanta", "mangahanta.com", "TR"],
			["all.mmrcms (my manga reader cms)", "Fallen Angels Scans", "truyen.fascans.com", "VI"],
			["all.webtoons", "Webtoons", "webtoons.com", "Multi"],
			["all.webtoons", "Dongman Manhua", "www.dongmanmanhua.cn", "ZH"],
			["all.wpmangastream", "MangaSwat", "mangaswat.com", "AR"],
			["all.wpmangastream", "Kiryuu", "kiryuu.co", "ID"],
			["all.wpmangastream", "KomikAV", "komikav.com", "ID"],
			["all.wpmangastream", "KomikCast", "komikcast.com", "ID"],
			["all.wpmangastream", "KomikIndo", "www.komikindo.web.id", "ID"],
			["all.wpmangastream", "KomikStation", "komikstation.com", "ID"],
			["all.wpmangastream", "MaidManga", "www.maid.my.id", "ID"],
			["all.wpmangastream", "SekteKomik", "sektekomik.com", "ID"],
			["all.wpmangastream", "WestManga", "westmanga.info", "ID"],
			["en.holymanga", "HeavenManga", "heavenmanga.org", "EN"],
			["en.holymanga", "HolyManga", "holymanga.net", "EN"],
			["en.mangareader", "MangaPanda", "www.mangapanda.com", "EN"],
			["en.mangareader", "MangaReader", "www.mangareader.net", "EN"],
			["pt.mangasproject", "MangaLivre", "mangalivre.net", "PT"],
			["pt.mangasproject", "mangásPROJECT", "leitor.net", "PT"],
		],
		settings: {
		  licenseKey: "non-commercial-and-evaluation",
		  readOnly: true,
		  colHeaders: [
			["Extension"],
			["Source Name"],
			["Source Website"],
			["Language"],
		  ],
		}
      };
	},
    components: {
      HotTable
    }
  }
</script>

<style lang="stylus">
div.wtHider
	max-width $contentWidth
	pointer-events none
	padding-bottom 3rem
</style>
